name: Setup Python Environment

on:
    workflow_call:
        inputs:
            python-version:
                required: true
                type: string

jobs:
    setup-python:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ inputs.python-version }}

            # Restaurar caché antes de instalar dependencias
            - name: Cache dependencies
              id: pip-cache
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ inputs.python-version }}-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-${{ inputs.python-version }}-

            # Instalar dependencias solo si no están en caché
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
